kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.claimName }}
  labels:
    app.kubernetes.io/name: {{ .Values.appName }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}