apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  labels:
    app.kubernetes.io/name: {{ .Values.appName }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  selector:
    app.kubernetes.io/name: {{ include "mysql.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Values.appName }}
    tier: {{ .Values.tier }}
