apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "godel-wordpress.fullname" . }}
  labels:
{{ include "godel-wordpress.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "godel-wordpress.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      tier: {{ .Values.tier }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "godel-wordpress.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        tier: {{ .Values.tier }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "godel-wordpress.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: WORDPRESS_DB_HOST
            value: {{ .Values.dbhost }}
          valueFrom:
            secretKeyRef:
              name: passwordsql
              key: password
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
          - name: wordpress-persistent-storage
            mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: {{ .Values.claimName }}

