kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.claimName }}
  labels:
{{ include "godel-wordpress.labels" . | indent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}