{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "godel-wordpress.serviceAccountName" . }}
  labels:
{{ include "godel-wordpress.labels" . | indent 4 }}
{{- end -}}
