apiVersion: v1
kind: Service
metadata:
  name: {{ include "godel-wordpress.fullname" . }}
  labels:
{{ include "godel-wordpress.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  selector:
    app.kubernetes.io/name: {{ include "godel-wordpress.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    tier: {{ .Values.tier }}
